import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FloatingWhatsapp from "./FloatingWhatsapp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children} 
      <FloatingWhatsapp 
      phoneNumber="5545998370965"
      messageArray={[
          'Olá, como posso te ajudar?',
          'Isso é só um teste Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum dicta fugit itaque neque beatae iure nobis a cupiditate aut, praesentium cumque ipsam commodi illum temporibus nulla animi suscipit, incidunt eius.',
          'Isso é só um teste Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum dicta fugit itaque neque beatae iure nobis a cupiditate aut, praesentium cumque ipsam commodi illum temporibus nulla animi suscipit, incidunt eius.',
          'Isso é só um teste Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum dicta fugit itaque neque beatae iure nobis a cupiditate aut, praesentium cumque ipsam commodi illum temporibus nulla animi suscipit, incidunt eius.'
      ]}
      headerTitle='Loumar Turismo'
      />
      </body>
    </html>
  );
}
